---
- name: Editors
  become: true
  tags: common, editors
  apt: pkg={{ item }} state=present
  with_items:
    - vim-gtk
    - emacs

- name: Vim install Vundle plugin manager
  tags: common, editors
  git: 
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

- name: Vim copy vimrc
  tags: common, editors
  template:
    src: ../../common/templates/vimrc
    dest: ~/.vimrc

- name: Emacs config directory
  tags: common, editors
  file:
    path: ~/.emacs.d
    state: directory

- name: Emacs copy config file
  tags: common, editors
  template:
    src: ../../common/templates/emacs.el
    dest: ~/.emacs.d/init.el
