---
- name: Editors
  become: true
  tags: common, editors
  apt: pkg={{ item }} state=present
  with_items:
    - vim-gtk
    - emacs

- name: Vim install Vundle plugin manager
  tags: common, editors
  git: 
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

- name: Vim copy vimrc
  tags: common, editors
  template:
    src: ../../common/templates/vimrc
    dest: ~/.vimrc

- name: Emacs config and org-mode folder
  tags: common, editors
  file:
    path: "~/{{ item }}"
    state: directory
  with_items:
    - org
    - .emacs.d

- name: Emacs config directory
  tags: common, editors
  copy:
    src: "{{ role_path }}/templates/emacs.d/"
    dest: ~/.emacs.d/

- name: Emacs org-mode agendas
  file:
    path: "~/org/{{ item }}.org"
    state: touch
  with_items:
    - personal
    - home
    - projects

