---
- name: Add contirb repository proper
  become: true
  apt_repository:
    repo: deb http://httpredir.debian.org/debian jessie main contrib non-free
    state: present

- name: Add contirb repository sources
  become: true
  apt_repository:
    repo: deb-src http://httpredir.debian.org/debian jessie main contrib non-free
    state: present

- name: Update apts cache
  become: true
  apt: update_cache=yes
  tags: common

- name: Add source for virtualbox guest util/etc
  become: true
  tags: common
  apt: pkg={{ item }} state=present
  with_items:
    - virtualbox-guest-dkms
    - virtualbox-guest-utils
    - virtualbox-guest-x11

- name: Downloads directory
  tags: common
  file:
    path: downloads
    state: directory

- name: General command line tools
  become: true
  tags: common
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - wget
    - git # Strictly speaking for development, but we use it all over
    - gawk
    - gettext
    - tree

- name: More descriptive welcome screen
  become: true
  tags: common
  template:
    src: templates/motd
    dest: /etc/motd
    mode: "u=rw,g=r,o=r"
    owner: root
    group: root

- include: ./tmux.yml
- include: ./zsh.yml
- include: ./x11.yml
- include: ./editors.yml
- include: ./firefox.yml # This is basically for Debian Jessie
- include: ./math.yml
