---
- name: Tmux install
  become: true
  tags: common, tmux
  apt: pkg=tmux state=present

- name: Tmux configuration file
  tags: common, tmux
  template:
    src: templates/tmux.conf
    dest: ~/.tmux.conf

- name: Tmux TPM install
  tags: commmon, tmux
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

