---
- name: CMake latest get
  tags: dev, cmake
  get_url:
    url: https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.sh
    dest: ~/downloads/cmake-3.7.1

- name: CMake install script
  tags: dev, cmake
  template:
    src: templates/cmake.installation.sh
    dest: ~/downloads/.
    mode: "u=rwx,g=r,o=r"

- name: CMake latest install
  tags: dev, cmake
  become: true
  shell: ./cmake.installation.sh warn=no
  register: cmakeinstall
  args:
    chdir: /home/{{ ansible_user }}/downloads
    executable: /bin/bash
    creates: /usr/bin/cmake

#- debug: msg="{{ cmakeinstall.stdout }}"
#- debug: msg="{{ cmakeinstall.stderr }}"

- name: Vim check for existance
  tags: development, ide, editors
  stat: path=~/.vimrc
  register: vimrc

- name: Vim include cmake/completion plugins
  tags: dev, editors, ide, cmake
  when: false and vimrc.stat.exists
  lineinfile:
    dest: ~/.vimrc
    insertafter: '" ------ Plugins go here ------'
    line: "{{ item }}"
  with_items:
    - "    Plugin 'pbettch/vim-cmake-syntax'"
    - "    Plugin 'valloric/youcompleteme'"
    - '    "   --- Development: completion/cmake dependencies ---   '
