---
- name: CMake latest get
  tags: dev, cmake
  get_url:
    url: https://cmake.org/files/v3.7/cmake-3.7.1-Linux-x86_64.sh
    dest: /home/vagrant/downloads/cmake-3.7.1

- name: CMake latest install
  tags: dev, cmake
  become: true
  shell: |
    yes | /bin/bash /home/vagrant/downloads/cmake-3.7.1 --prefix=/opt --include-subdir
    if [ ! -f /usr/bin/cmake ]; then
      ln -f -s /opt/cmake-3.7.1-Linux-x86-84/bin/cmake /usr/bin/.
      ln -f -s /opt/cmake-3.7.1-Linux-x86-84/bin/cpack /usr/bin/.
      ln -f -s /opt/cmake-3.7.1-Linux-x86-84/bin/cmake-gui /usr/bin/.
      ln -f -s /opt/cmake-3.7.1-Linux-x86-84/bin/ccmake /usr/bin/.
      ln -f -s /opt/cmake-3.7.1-Linux-x86-84/bin/ctest /usr/bin/.
    fi

