---
- name: General building
  tags: dev
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - jq # Very nice for json viewing/searching
    - make
    - binutils
    - autoconf
    - automake
    - build-essential
    - devscripts
    - python-software-properties
    - pkg-config
    - nfs-common
    - libtool
    - libxml2
    - libxml2-dev
    #- libxslt
    #- libxslt-dev
    - expect-dev
    - libunwind8
    # LMD> The following are useful for debugging
    - inotify-tools
    - iotop
    - htop
    - iptraf 
    # LMD> Need a way to configure wireshark's installation
    #- wireshark

- include: ./git.yml
- include: ./go.yml
- include: ./perl.yml
- include: ./cmake.yml
- include: ./rust.yml
- include: ./ruby.yml
- include: ./python.yml
- include: ./node.yml
- include: ./erlang.yml
- include: ./java.yml
- include: ./vscode.yml
- include: ./mono.yml
- include: ./ide.yml
