---
- name: Python
  tags: dev, python
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - python
    - python3
    - python-pip
    - python3-pip
    - python-dev
    - python3-dev
    - python-matplotlib
    - python3-matplotlib
    - python-setuptools
    - python3-setuptools
    - python-scipy
    - python3-scipy
    - python-numpy
    - python3-numpy
    - idle
    - idle3
    - python-pandas
    - python3-pandas
