---
- name: Python
  tags: dev, python
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - python
    - python3
    - python-pip
    - python3-pip
    - python-dev
    - python3-dev
    - python-matplotlib
    - python3-matplotlib
    - python-setuptools
    - python3-setuptools
    - python-scipy
    - python3-scipy
    - python-numpy
    - python3-numpy
    - idle
    - idle3
    - python-pandas
    - python3-pandas
    - python-dateutil
    - python3-dateutil

- name: Vim check for existance
  tags: development, ide, editors
  stat: path=~/.vimrc
  register: vimrc

- name: Vim add python goodies
  tags: development, ide, editors
  when: vimrc.stat.exists
  lineinfile:
    state: present
    dest: ~/.vimrc
    insertafter: "------ Plugins go here ------"
    line: "{{ item }}"
  with_items:
      - "    Plugin 'scrooloose/syntastic'"
      - "    let python_highlight_all=2"
      - "    Plugin 'nvie/vim-flake8'"
      - "    Plugin 'vim-scripts/indentpython.vim'"
      - "    \"     - Development: python: PEP8 identation -    "
      - "    let g:SimpylFold_docstring_preview=1"
      - "    Plugin 'tmhedberg/SimpylFold'"
      - "   \"   --- Development: python ---  "
