---
- name: Rust get
  tags: dev, rust
  git:
    repo: https://github.com/rust-lang/rust.git
    dest: ~/downloads/rust

- name: Rust compile
  tags: dev, rust
  become: true
  shell: |
    ./configure
    make install
  args: 
    executable: /bin/bash
    chdir: /home/{{ ansible_user }}/downloads/rust
