set nocompatible             " don't bother about vi compatibility, full vim
filetype off

set background=dark
colorscheme koehler

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'

    " ------ Plugins go here ------

    "   --- Javascript ---
    Plugin 'pangloss/vim-javascript'
    Plugin 'mxw/vim-jsx'
    Plugin 'leafgarland/typescript-vim'
    Plugin 'Quramy/vim-js-pretty-template'

    Plugin 'nathanaelkane/vim-indent-guides'
    Plugin 'kien/ctrlp.vim'
    Plugin 'scrooloose/nerdtree'
    Plugin 'bling/vim-airline'
    Plugin 'tpope/vim-surround'
    Plugin 'tpope/vim-fugitive'
    Plugin 'Shougo/vimproc.vim'
    Plugin 'Shougo/unite.vim'

    Plugin 'valloric/youcompleteme'
call vundle#end()


set laststatus=2
set backspace=2
set nobackup
set nowritebackup
set title
set viminfo='1000,n~/.vim/_viminfo'
set showcmd

syntax enable                 " enable syntax processing
set tabstop=4                 " number of visual spaces per TAB
set softtabstop=4             " number of spaces in tab when editingo
filetype plugin indent on     " load file-type specific indentetion settings
set number                    " show line numbers
set cursorline
set wildmenu                  " visual autocomplete for command menu
set lazyredraw                " redraw only when needed
set showmatch                 " highlight matching parenthesis
set incsearch                 " search as characters are entered
set hlsearch                  " highlight search matches
set foldenable                " enable folding
set foldlevelstart=10         " opens most folds by default
set foldnestmax=10            " 10 nested folds as a maximum

" space toggles folds
nnoremap <space> za           
" ,<space> stops highlighting search matches
nnoremap <leader><space> :nohlsearch<CR> 
set foldmethod=marker         " fold based on identation level

" Much from http://dougblack.io/words/a-good-vimrc.html
augroup configgroup
    autocmd!
    autocmd VimEnter * highlight clear SignColumn
    autocmd FileType java setlocal noexpandtab
    autocmd FileType java setlocal list
    autocmd FileType java setlocal listchars=tab:+\ ,eol:-
    autocmd FileType java setlocal formatprg=par\ -w80\ -T4
    autocmd FileType php setlocal expandtab
    autocmd FileType php setlocal list
    autocmd FileType php setlocal listchars=tab:+\ ,eol:-
    autocmd FileType php setlocal formatprg=par\ -w80\ -T4
    autocmd FileType ruby setlocal tabstop=2
    autocmd FileType ruby setlocal shiftwidth=2
    autocmd FileType ruby setlocal softtabstop=2
    autocmd FileType ruby setlocal commentstring=#\ %s
    autocmd FileType python setlocal commentstring=#\ %s
    autocmd BufEnter *.cls setlocal filetype=java
    autocmd BufEnter *.zsh-theme setlocal filetype=zsh
    autocmd BufEnter Makefile setlocal noexpandtab
    autocmd BufEnter *.sh setlocal tabstop=2
    autocmd BufEnter *.sh setlocal shiftwidth=2
    autocmd BufEnter *.sh setlocal softtabstop=2
    autocmd FileType *.js setlocal shiftwidth=2
augroup END

set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe
au FileType javascript call JavaScriptFold()
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4

map <F5> :e<CR>
map <F2> :NerdTreeToggle<CR>
map <C-f2> :source ~/.vimrc<CR>
